### ISSUE TITLE
Support per-job stream selection

### ISSUE THREAD

**Issue by DavidYKay** [jenkinsci/zulip-plugin#1]
Currently the plugin only supports notifying one global stream. 

We use "jenkins," but this gets messy as everyone looks to the one central stream.

It'd be nicer if we could have different Jenkins jobs routing their updates to different Humbug streams, like with the GitHub hook.

**Comment by wdaher** [comment]
Thanks for the suggestion, David. I definitely agree that this makes sense.
I've opened this as issue #2326 in our internal tracker, and will keep you folks up to date.

**Comment by ogg1e** [comment]
Any progress on this? It's a feature that would be nice to have.

**Comment by timabbott** [comment]
No; a PR for this would be welcome though!

**Comment by butchyyyy** [comment]
PR #8 allows you to configure dfferent stream for each job.

**Comment by timabbott** [comment]
Closing as fixed by #8.
