### ISSUE TITLE
build of zulip-plugin fails because of deprecated method getTestResultAction

### ISSUE THREAD

**Issue by nestie** [jenkinsci/zulip-plugin#15]
A build of zulip-plugin failed with error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project humbug: Compilation failure
[ERROR] /var/lib/jenkins/zulip-plugin/src/main/java/hudson/plugins/humbug/HumbugNotifier.java:[104,38] cannot find symbol
[ERROR]   symbol:   method getTestResultAction()
[ERROR]   location: variable build of type hudson.model.Run<?,?>

According to https://javadoc.jenkins-ci.org/hudson/model/AbstractBuild.html the method is deprecated:
@Deprecated
public Action getTestResultAction()
Deprecated. Use Actionable.getAction(Class) on AbstractTestResultAction.

To fix this I've added the following to pom.xml:
    <dependency>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>junit</artifactId>
        <version>1.7</version>
    </dependency>

and changed src/main/java/hudson/plugins/humbug/HumbugNotifier.java by adding the import
import hudson.tasks.test.AbstractTestResultAction;
and changing
int failCount = build.getTestResultAction().getFailCount();
to
int failCount = build.getAction(AbstractTestResultAction.class).getFailCount();

**Comment by butchyyyy** [comment]
Thanks for reporting. This is a result of falsely merged PR that was made against the old version of the plugin that did not support pipelines (used AbstractBuild instead of Run in the notification processing).
It will befixed today.

**Comment by butchyyyy** [comment]
Fixed via 8a616e84dc7ad56554c2737dd1acc5aee9c36162

**Comment by nestie** [comment]
Great. Thanks
