### ISSUE TITLE
Enable Smart Notification is always selected

### ISSUE THREAD

**Issue by Philipp1909** [jenkinsci/zulip-plugin#17]
Version 1.0.1
function "Enable Smart Notification" is always selected automatically and I don't get a notification if the build fails or if the build is okay.
I have entered a stream and a topic in the post-build configuration.
![postbuild config](https://user-images.githubusercontent.com/42967341/53812488-e353bb00-3f5b-11e9-85c2-ea8e595f6907.JPG)

In the Zulip notification settings I have entered the zulip URL, Zulip User Email and the Zulip API Key.
![zulip notification settings](https://user-images.githubusercontent.com/42967341/53812732-5fe69980-3f5c-11e9-8e5a-c6f09c507075.JPG)

**Comment by butchyyyy** [comment]
Thanks for reporting that's definitely a regression introduced by version 1.0.1. I'll roll out a fix later today. Still even with smart notification checked, you should receive notifications for failed builds, so there must be another reason why your notifiactions fails to send.

Please check Troubleshooting section of https://zulipchat.com/integrations/doc/jenkins

Especially if you have the correct bot credentials and your bot is subscribed to the stream you want notifications posted to.
If that does not help, the best way to debug why messages fail to send is to enable log recorder in Jenkins for **jenkins.plugins.zulip**. Message that failed to send should be logged there with a reason.

**Comment by butchyyyy** [comment]
Just released 1.0.2 fixing the problem. Once again, it should be available in update center within 8 hours (earlier most likely 😉).

Thanks again for taking the time to report the issue and sorry for the caused inconvenience.

If you still have issues with notifications getting through, you can reach out via comment or at https://chat.zulip.org/
