### ISSUE TITLE
Plugin Version 1.0.1 does not sent any notifications to Zulip

### ISSUE THREAD

**Issue by Philipp1909** [jenkinsci/zulip-plugin#18]
Hello,
the plugin version 1.0.1 does not send any notifications to Zulip.
We are using a self-hosted installation and have configured a freestyle job in Jenkins. The exceptions for the proxy are also configured.
When starting the freestyle job the plugin does not react and there is no console output. 
Stream, topic, Bot E-Mail, Bot API are 100% correct.

Any ideas?

![Zulip Notification Settings](https://user-images.githubusercontent.com/42967341/54135549-4e990380-441a-11e9-91ea-9231e24b8758.JPG)
![Zulip post Build](https://user-images.githubusercontent.com/42967341/54135550-4e990380-441a-11e9-8690-02bd500c7345.JPG)

**Comment by butchyyyy** [comment]
Thanks for reporting.
Do i understand correctly that your self-hosted Zulip server is not reachable via proxy and you have it listed in the no proxy hosts (exceptions).
I think those settings are not applied in the plugin. There was a [PR](https://github.com/jenkinsci/humbug-plugin/pull/3) opened for the plugin predecessor.
I'll do some testing and should be able to roll out a fix soon.

**Comment by butchyyyy** [comment]
@Philipp1909 If you can please confirm the proxy assumption?

Also can you double check your log recorder output? If the message fails to go through you should defintely see something there. E.g. here's an error output when bad host is specified in Zulip Url configuration. For other unexpected errors the job itself should fail.

![image](https://user-images.githubusercontent.com/17402486/54197957-93c63f80-44c5-11e9-8ddd-e26a48fe7051.png)

**Comment by Philipp1909** [comment]
For our self hosted Zulip server a proxy is set up. Webhooks from our Jira system, for example, work without problems. The Jenkins Log Recorder shows me the following error message, both in the private stream and in the public stream and in both streams the bot is registered as user.

![stream closed](https://user-images.githubusercontent.com/42967341/54201488-0b986800-44ce-11e9-82d3-ce4a2b45789a.JPG)

If the build is successful and the build is faulty Tomcat catalina.out shows the following log errors:

12-Mar-2019 13:44:28.931 INFO [Executor #0 for master : executing ZulipFreestyleTest #33] hudson.model.Run.execute ZulipFreestyleTest #33 main build action completed: SUCCESS
12-Mar-2019 13:44:28.934 SEVERE [Executor #0 for master : executing ZulipFreestyleTest #33] jenkins.plugins.zulip.Zulip.post Error sending Zulip message: Stream closed

**Comment by butchyyyy** [comment]
Thanks for providing the details @Philipp1909 
I managed to reproduce the ```Error sending Zulip message: Stream closed``` error when proxy is configured in Jenkins instance.
I should have a fix ready tomorrow.

**Comment by butchyyyy** [comment]
@Philipp1909 I have published version 1.0.3 Proxy fixes. It is now available in the update center (don't forget to update the plugin index).
The plugin now respects the no proxy hosts settings and also passes the user name password credentials to the proxy if set.

Please let me know if it helps.

**Comment by Philipp1909** [comment]
Now it works well! Thanks for your Support @butchyyyy
