### ISSUE TITLE
Environment variables are not resolved

### ISSUE THREAD

**Issue by k-spa** [jenkinsci/zulip-plugin#19]
Hello,

currently, it seems that the plugin only allows using a fixed value for the stream/topic name (I'm using the "Zulip notification" post-build action, if that matters).

It would be really nice to be able to use environment variables (e.g. $BRANCH_NAME in order to dynamically change where the zulip notification is being posted to.

Thanks!

**Comment by butchyyyy** [comment]
Sorry for the late reply, was on vacation.

Since the environments variables are already supported in Zulip Send message, i see no problem supporting them in stream and topic name aswell.

I'll make the changes and roll out new version sometime this week. Will keep you posted.

**Comment by butchyyyy** [comment]
I just released new version 1.1.0 that now expands jenkins build variables in stream and topic name. The  new release should show in the update center in few hours.

Sorry this came later than advocated, I was really swamped with work / family.
