### ISSUE TITLE
Feature request: possibility to configure smart notifications per Jenkins job.

### ISSUE THREAD

**Issue by patzi** [jenkinsci/zulip-plugin#21]
It would be nice to have the ability to configure the smart notification property per Jenkins Job. 
There are two possibilities:
- The system wide setting would be the default for new jobs.
- the setting in systems would be gone and it needed to be enabled for every new job.
The second possibility would be easier to implement but then it would be harder to enable for every project.
What do you think of this? Maybe I will find some time in the future to look into a pull request for this.

**Comment by butchyyyy** [comment]
This definitely makes sense. I don’t want to get rid of the global settings so the check box would stay there and I would add a new post build step configuration.

The step smart notifications configuration would be a three value dropdown (or radio group, not sure about that yet – let me know what do you think is better) with following options:
- Use global settings
- Yes
- No

I’ll try to work on it as soon as possible.

**Comment by butchyyyy** [comment]
Sorry it took so long - benn super busy. The feature is now implemented and will be part of the next plugin release.

**Comment by patzi** [comment]
Thanks for your work. I know the busy part by myself, its always hard to find time for non essential problems.
