### ISSUE TITLE
Zulip notifications in one job are blocked by the other job

### ISSUE THREAD

**Issue by volo-zyko** [jenkinsci/zulip-plugin#24]
If there are 2 jobs and one of them finishes earlier then Zulip notifications block until the other job finishes too. Exactly the same issue was fixed in the [Slack](https://github.com/jenkinsci/slack-plugin/pull/121) plugin. Fix for Zulip plugin is exactly the same. `getRequiredMonitorService` should return `BuildStepMonitor.NONE`. I tested it on my Jenkins.

**Comment by butchyyyy** [comment]
Thanks for reporting! Fixed and will be part of the next release.
