### ISSUE TITLE
Failed builds should use :cross_mark: rather than :x:

### ISSUE THREAD

**Issue by tbroyer** [jenkinsci/zulip-plugin#26]
With Zulip's "Google modern" emoji theme (which I think is the default), in Zulip 3.1, the `:x:` displays as a cross in a *green* box (seems to match Android 10: https://emojipedia.org/google/android-10.0/cross-mark-button/, Android 9 and Android 11 had/have a red cross in a black-bordered white box, looking like what was displayed in Zulip 2.x)

I'd suggest using `:cross_mark:` instead, which is more consistently displayed in red: https://emojipedia.org/cross-mark/

Moreover, a successful build uses `:check_mark:`, which is not in a box: https://emojipedia.org/check-mark/ so it would be more consistent.

**Comment by timabbott** [comment]
@tbroyer thanks for the feedback!  What integration are you seeing us using `:x:` with?  `git grep ':x:'` returns no results in our main codebase.

**Comment by timabbott** [comment]
Oh, sorry, I missed the repository was the Jenkins plugin.  Sorry for the confusion!  Yes, this sounds like a good change.

**Comment by timabbott** [comment]
Want to submit a PR?  I imagine @butchyyyy will review/merge and then get a release to happen.

**Comment by butchyyyy** [comment]
Just released version 1.2.1 that replaces the emoji for failed builds as proposed by @tbroyer . Should be available via Jenkins update center in few hours.

Thanks for reporting!

**Comment by tbroyer** [comment]
Thank you!

On a side note, here in France, I reported the issue at 6pm :clock630: just after I saw my build failure notification in our Zulip instance at work, it was fixed and released by midnight :clock12: :rocket:, and a coworker installed it this morning even before I started working :clock830: :tada: 
Fixed overnight!
