### ISSUE TITLE
Support publishing to arbitrary Zulip servers

### ISSUE THREAD

**Issue by wdaher** [jenkinsci/zulip-plugin#4]
Rather than only letting you configure servers of the form xyz.zulip.com, you should be able to specify an arbitrary server in the configuration field.

**Comment by timabbott** [comment]
This should be really easy to do if anyone's interested!

**Comment by wolfen351** [comment]
Who ever did this and released the update, I just want to say THANKS! :D :dancers: 

For those reading this, the latest version available via the jenkins plugin manager fixes this issue

**Comment by wdaher** [comment]
Thanks! Glad to hear that it's working well.

(I forgot that this was also being tracked here :))
