### ISSUE TITLE
Add ability to NOT fail the build if Zulip is down

### ISSUE THREAD

**Issue by wolfen351** [jenkinsci/zulip-plugin#5]
My zulip server is on a non UPS protected machine, so every now and again the zulip instance goes down. I want to be able to "ignore" failure to post to zulip - i.e. write some warning in the console output of the log but not actually fail the build

**Comment by timabbott** [comment]
Hmm yeah that would be a great improvement.

**Comment by butchyyyy** [comment]
The build won't fail if plugin receives a non 200 response from Zulip, but will fail if Zulip server can't be reached (IOException).
I agree that this is a bug and both cases should be handled same = log the error, but don't fail the build. I'll submit a PR with the fix soon.
In the future we could add a "Fail build when message to Zulip fails to send" check box, but for now i would not bloat the configuration unless someone specifically asks for it.
