### ISSUE TITLE
Support DSL

### ISSUE THREAD

**Issue by pixie79** [jenkinsci/zulip-plugin#6]
Hi,

It would be good if the zulip plugin supported the job-dsl-plugin so that when we build our jobs via DSL we can enable Zulip notifications automatically.

https://github.com/jenkinsci/job-dsl-plugin/wiki/Extending-the-DSL

Thanks

Mark

**Comment by DoCode** [comment]
What about Jenkins Pipeline syntax?

**Comment by lfaraone** [comment]
> What about Jenkins Pipeline syntax?

please open a separate issue on the main https://github.com/zulip/zulip repository

**Comment by timabbott** [comment]
@lfaraone why would an issue on zulip/zulip be the right place to ask about Jenkins Pipeline syntax?

I think a separate issue in this project makes more sense, but @DoCode you should provide more clarity about what you're trying to do; I don't think anyone's going to be able to help with such a brief description of your issue.

**Comment by timabbott** [comment]
Back to the original issue: Contributions welcome!  This project is a small plugin, so it's a great place to get involved in contributing open source.

**Comment by timabbott** [comment]
@DoCode and others: I believe pipeline syntax was added via https://github.com/zulip/zulip-jenkins-plugin/pull/8.

**Comment by butchyyyy** [comment]
There's no explicit DSL support, but Zulip steps can be used just fine by the [dynamically generated DSLs](https://github.com/jenkinsci/job-dsl-plugin/wiki/Dynamic-DSL)

Example of DSL creating frestyle job using both Zulip Send and Zulip Notification:


```jenkins
job('DSL-Freestyle') {
  steps {
    zulipSend {
      message('Hello DSL!')
      stream('sandbox')
      topic('dsl')
    }
  }
  publishers {
    zulipNotification {
      stream('sandbox')
      topic('dsl')
    }
  }
}
```
I think we can close this one.

**Comment by timabbott** [comment]
Cool.  Closing, though should we add a section to the README documentation with that example on how to do job DSLs so it's easy to find?
